#!/bin/bash

function updo() {
  if git check-ignore -q "$1"; then
    exit
  fi

  (./strip-license.py <"$1" >"$1.tmp") || (echo "Unable to update snippets for $1" && exit 1)
  if diff -q "$1.tmp" "$1" >/dev/null; then
    rm "$1.tmp" || (echo "Unable to remove temp file" && exit 1)
  else
    mv "$1.tmp" "$1" && git add "$1" || (echo "Unable to copy content" && exit 1)
  fi
}

export -f updo
find src/ -name \*.js -exec bash -c 'updo "$0"' {} \; || (echo "find failed" && exit 1)
