# Continuous integration builds

env:
  AWS_ACCOUNT_ALIAS: common
  ENVIRONMENT_NAME: common
  DEPLOY_ENVIRONMENT_NAME: production
  S3_HOSTNAME: demos.developer.virtru.com
  USE_NODE_12: true

steps:
  - label: ':gear: build & unit test'
    commands:
      - buildkite-agent pipeline upload .buildkite/pre.yml
