
env:
  AWS_ACCOUNT_ALIAS: common
  ENVIRONMENT_NAME: common
  DEPLOY_ENVIRONMENT_NAME: production
  TEST_ENVIRONMENT_NAME: production
  S3_HOSTNAME: demos.developer.virtru.com
  USE_NODE_18: true

steps:
  - label: ':gear: build & run tests'
    command: 'buildkite-agent pipeline upload .buildkite/pr.yml'
