# Deploy using gitflow
#
# Basic idea:
# * Developers almost always patch to master first.
# * Releases happen on a branch
# * They can cherry-pick (or ffwd-merge, aka no-fault rebase) to releases
# * Once a release goes out it is tagged. Tags are on releases, these may or
#   may not be in a history.
#
# Where do deployments go:
# master -> develop01
# feature/* -> develop[X] after select
# release/* -> staging
# v* -> production after block & shout

env:
  AWS_ACCOUNT_ALIAS: common
  ENVIRONMENT_NAME: common
  DEPLOY_ENVIRONMENT_NAME: production
  TEST_ENVIRONMENT_NAME: production
  S3_HOSTNAME: demos.developer.virtru.com
  USE_NODE_16: true

steps:
  # This step immediately runs an e2e test on branches named *e2e*
  # The purpose is to allow test developers to quickly check test validity
  - label: ':chrome: early E2E Tests: $TEST_ENVIRONMENT_NAME'
    branches: '*e2e*'
    command: 'npm run test-e2e'
    artifact_paths: 'e2e/reports/*'
    concurrency: 3
    concurrency_group: 'desktop-chrome-sdk'

  - label: ':gear: build & unit test'
    commands:
      - buildkite-agent pipeline upload .buildkite/pre.yml

  - wait

  - label: ':gear: :rocket: develop'
    trigger: protect-and-track-deploy
    build:
      message: '[develop] ${BUILDKITE_MESSAGE}'
      commit: '${BUILDKITE_COMMIT}'
      branch: '${BUILDKITE_BRANCH}'
      env:
        BLOCK_DEPLOY: 'build.branch =~ /^feature\//'
        OIDC_CLIENT_ID: '${OIDC_CLIENT_ID_DEVELOP}'
        S3_PATH: protect-develop
        VIRTRU_ENV: ${VIRTRU_ENV:-develop01}
    branches: master feature/*

  - wait

  - label: ':gear: :rocket: staging'
    trigger: protect-and-track-deploy
    build:
      message: '[staging] ${BUILDKITE_MESSAGE}'
      commit: '${BUILDKITE_COMMIT}'
      branch: '${BUILDKITE_BRANCH}'
      env:
        BLOCK_DEPLOY: 'build.branch == "master"'
        OIDC_CLIENT_ID: '${OIDC_CLIENT_ID_STAGING}'
        S3_PATH: 'protect-staging'
        VIRTRU_ENV: staging
    branches: 'master release/*'

  - wait

  - label: ':gear: :rocket: production [blocked]'
    trigger: protect-and-track-deploy
    build:
      message: '[production] ${BUILDKITE_MESSAGE}'
      commit: '${BUILDKITE_COMMIT}'
      branch: '${BUILDKITE_BRANCH}'
      env:
        OIDC_CLIENT_ID: '${OIDC_CLIENT_ID_PRODUCTION}'
        S3_PATH: 'protect'
        VIRTRU_ENV: production
    branches: 'release/*'

  - wait

  - block: 'Tag release?'
    branches: 'release/*'

  - label: 'Tag Release'
    command: '.buildkite/scripts/cut-release.sh'
    branches: 'release/*'
