# Deploy using gitflow
#
# Basic idea:
# * Developers almost always patch to master first.
# * Releases happen on a branch
# * They can cherry-pick (or ffwd-merge, aka no-fault rebase) to releases
# * Once a release goes out it is tagged. Tags are on releases, these may or
#   may not be in a history.
#
# Where do deployments go:
# master -> develop01
# feature/* -> develop[X] after select
# release/* -> staging
# v* -> production after block & shout

env:
  AWS_ACCOUNT_ALIAS: common
  ENVIRONMENT_NAME: common
  DEPLOY_ENVIRONMENT_NAME: production
  S3_HOSTNAME: demos.developer.virtru.com
  USE_NODE_12: true

steps:
  - label: ':npm: Install Dependencies'
    command: 'buildkite-scripts/mars/wrap/npm-ci.sh'

  - wait

  - label: ':npm: :lock: NPM Audit'
    command: '.buildkite/scripts/npm-audit.sh'

  - wait

  - label: ':npm: Tests'
    command: 'buildkite-scripts/scripts/npm-test.sh'
    artifact_paths:
      - 'coverage/lcov.info'

  - wait

  - label: ':house_with_garden: Create block for deploy environment selection'
    branches: 'feature/* hotfix/*'
    command: 'buildkite-scripts/mars/pipeline-steps/get-and-select-develop-environments.sh | buildkite-agent pipeline upload'

  - wait

  - label: ':house_with_garden: Set Environment'
    command: 'buildkite-scripts/mars/scripts/set-deploy-environment.sh'
    branches: 'master release/* feature/* hotfix/*'

  - wait

  - label: ':gear: :rocket: develop'
    commands:
      - buildkite-agent pipeline upload .buildkite/ci.yml
    env:
      BLOCK_DEPLOY: 'build.branch =~ /^feature\//'
      VIRTRU_ENV: develop01
      S3_PATH: protect-develop
    branches: master feature/*

  - wait

  - label: ':gear: :rocket: staging'
    commands:
      - buildkite-agent pipeline upload .buildkite/ci.yml
    env:
      BLOCK_DEPLOY: 'build.branch == "master"'
      VIRTRU_ENV: staging
      S3_PATH: 'protect-staging'
    branches: 'master release/*'

  - wait

  - label: ':gear: :rocket: production [blocked]'
    commands:
      - buildkite-agent pipeline upload .buildkite/ci.yml
    env:
      VIRTRU_ENV: production
      S3_PATH: 'protect/'
    branches: 'release/*'

  - wait

  - block: 'Tag release?'
    branches: 'release/*'

  - label: 'Tag Release'
    command: '.buildkite/scripts/cut-release.sh'
    branches: 'release/*'
