# Build validation and unit tests; to be run before merging code.

env:
  AWS_ACCOUNT_ALIAS: ${AWS_ACCOUNT_ALIAS}
  ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
  DEPLOY_ENVIRONMENT_NAME: ${DEPLOY_ENVIRONMENT_NAME}
  S3_HOSTNAME: ${S3_HOSTNAME}
  USE_NODE_16: ${USE_NODE_16:-}

steps:
  - label: ':npm: Install Dependencies'
    command: 'buildkite-scripts/mars/wrap/npm-ci.sh'

  - wait

  - label: ':npm: :lock: NPM Audit'
    command: '.buildkite/scripts/npm-audit.sh'

  - wait

  - label: ':npm: Tests'
    command: 'buildkite-scripts/scripts/npm-test.sh'
    artifact_paths:
      - 'coverage/lcov.info'

  - label: ':npm: Validate NPM Build'
    command: 'buildkite-scripts/scripts/npm-build.sh'
