export default {
  OTHER: 'Other',
  'EMAIL.DRAFTED': 'Secure Email Drafted',
  'EMAIL.SENT': 'Secure Email Sent',
  'EMAIL.FORWARDED': 'Secure Email Forward',
  'EMAIL.ACCESS_SUCCEEDED': 'Secure Email Accessed',
  'EMAIL.ACCESS_FAILED': 'Secure Email Access Denied',
  'EMAIL.REVOKED': 'Secure Email Revoke',
  'EMAIL.EXPIRATION_ENABLED': 'Secure Email Expiration Set',
  'EMAIL.EXPIRATION_DISABLED': 'Secure Email Expiration Disabled',
  'EMAIL.FORWARD_DISABLED': 'Secure Email Forwarding Disabled',
  'EMAIL.FORWARD_ENABLED': 'Secure Email Forwarding Enabled',
  'EMAIL.WATERMARK_ENABLED': 'Secure Email Watermark Enabled',
  'EMAIL.WATERMARK_DISABLED': 'Secure Email Watermark Disabled',
  'EMAIL.ONE_CLICK_ENABLED': 'Secure Email One Click Enabled',
  'EMAIL.ONE_CLICK_DISABLED': 'Secure Email One Click Disabled',
  'EMAIL.FILE_ATTACHED': 'Secure File Attached',
  'EMAIL.REAUTHORIZED': 'Secure Email Reauthorized',
  'RULE.CREATED': 'Rule Created',
  'RULE.UPDATED': 'Rule Updated',
  'RULE.TRIGGERED': 'Rule Triggered',
  'RULE.DELETED': 'Rule Deleted',
  'RULE.CREATE_ERROR': 'Rule Create Error',
  'RULE.UPDATE_ERROR': 'Rule Update Error',
  'RULE.OVERRIDDEN': 'Rule Overridden',
  'INVITATION.SENT': 'Invitation Sent',
  'INVITATION.ACCEPTED': 'Invitation Accepted',
  'INVITATION.UPDATED': 'Invitation Updated',
  'INVITATION.REVOKED': 'Invitation Revoked',
  'INVITATION.CREATE_ERROR': 'Invitation Create Error',
  'INVITATION.UPDATE_ERROR': 'Invitation Update Error',
  'ACTIVATION.STARTED': 'Activation Started',
  'ACTIVATION.COMPLETED': 'Activation Completed',
  'ACTIVATION.UPDATED': 'Activation Updated',
  'ACTIVATION.REVOKED': 'Activation Revoked',
  'ACTIVATION.CREATE_ERROR': 'Activation Create Error',
  'ACTIVATION.UPDATE_ERROR': 'Activation Update Error',
  'UNIT.CREATED': 'OU/Group Created',
  'UNIT.UPDATED': 'OU/Group Updated',
  'UNIT.DELETED': 'OU/Group Deleted',
  'UNIT.CREATE_ERROR': 'OU/Group Create Error',
  'UNIT.UPDATE_ERROR': 'OU/Group Update Error',
  'ORGANIZATION.API_TOKEN_CREATED': 'API Token Created',
  'ORGANIZATION.CREATED': 'Organization Created',
  'ORGANIZATION.UPDATED': 'Organization Updated',
  'ORGANIZATION.KEY_CREATED': 'Encrypted Key Generated',
  'ORGANIZATION.KEY_REVOKED': 'Encrypted Key Revoked',
  'ORGANIZATION.CREATE_ERROR': 'Organization Create Error',
  'ORGANIZATION.UPDATE_ERROR': 'Organization Update Error',
  'POLICY.CREATED': 'Policy Created',
  'POLICY.UPDATED': 'Policy Updated',
  'POLICY.CREATE_ERROR': 'Policy Create Error',
  'POLICY.UPDATE_ERROR': 'Policy Update Error',
  'USER.CREATED': 'User Created',
  'USER.UPDATED': 'User Updated',
  'USER.CREATE_ERROR': 'User Create Error',
  'USER.UPDATE_ERROR': 'User Update Error',
  'FILE.ENCRYPTED': 'Secure File Encrypted',
  'FILE.ENCRYPTED_COPY': 'Secure File Encrypted (Copy)',
  'FILE.UPLOADED': 'Secure File Uploaded',
  'FILE.DECRYPTED': 'Secure File Decrypted',
  'FILE.DECRYPTED_COPY': 'Secure File Decrypted (Copy)',
  'FILE.DOWNLOADED': 'Secure File Downloaded',
  'FILE.ACCESS_SUCCEEDED': 'Secure File Accessed',
  'FILE.SHARED': 'Secure File Shared',
  'FILE.VERSION_ADDED': 'Secure Version Added',
  'FILE.VERSION_REMOVED': 'Secure Version Removed',
  'FILE.ACCESS_FAILED': 'Secure File Access Denied',
  'FILE.REVOKED': 'Secure File Revoke',
  'FILE.REAUTHORIZED': 'Secure File Reauthorized',
  'FILE.EXPIRATION_ENABLED': 'Secure File Expiration Set',
  'FILE.EXPIRATION_DISABLED': 'Secure File Expiration Disabled',
  'FILE.SHARING_ENABLED': 'Secure File Resharing Enabled',
  'FILE.SHARING_DISABLED': 'Secure File Resharing Disabled',
  'FILE.WATERMARK_ENABLED': 'Secure File Watermark Enabled',
  'FILE.WATERMARK_DISABLED': 'Secure File Watermark Disabled',
  'PERMISSION.SUPER_ADMIN_ADDED': 'Super Admin Added',
  'PERMISSION.POLICY_ADMIN_ADDED': 'Policy Admin Added',
  'PERMISSION.USER_ADMIN_ADDED': 'User Admin Added',
  'PERMISSION.CONTENT_ADMIN_ADDED': 'Content Admin Added',
  'PERMISSION.EDISCOVERY_ADMIN_ADDED': 'eDiscovery Admin Added',
  'PERMISSION.SUPER_ADMIN_REMOVED': 'Super Admin Removed',
  'PERMISSION.POLICY_ADMIN_REMOVED': 'Policy Admin Removed',
  'PERMISSION.USER_ADMIN_REMOVED': 'User Admin Removed',
  'PERMISSION.CONTENT_ADMIN_REMOVED': 'Content Admin Removed',
  'PERMISSION.EDISCOVERY_ADMIN_REMOVED': 'eDiscovery Admin Removed',
  'PERMISSION.USER_UPDATED': 'User Permissions Updated',
};
