#!/bin/bash

export APP_VERSION=$(cat package.json | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["version"];')
echo "+++ APP_VERSION: $APP_VERSION"

# set TEST_ENVIRONMENT_NAME based on BUILDKITE_BRANCH
case $BUILDKITE_BRANCH in
develop)
  export TEST_ENVIRONMENT_NAME=staging
  ;;
staging)
  export TEST_ENVIRONMENT_NAME=staging
  ;;
master)
  export TEST_ENVIRONMENT_NAME=production
  ;;
*)
  if buildkite-agent meta-data exists "deploy-environment-name"
  then
    export TEST_ENVIRONMENT_NAME=$(buildkite-agent meta-data get "deploy-environment-name")
  else
    export TEST_ENVIRONMENT_NAME=unknown
  fi
  ;;
esac

echo "+++ TEST_ENVIRONMENT_NAME: $TEST_ENVIRONMENT_NAME"
