#!/bin/bash
source buildkite-scripts/utils/logging.sh

set -eu

echo "--- :checkered_flag: Running pre-command for command ${BUILDKITE_COMMAND}"

if [[ "${BUILDKITE_LABEL}" = *"Tests"* ]]; then
  # We do this to prevent BK from uploading artifacts to s3
  export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION=""
fi
